libraries
```{r libraries}
library(lmerTest)
library(ordinal)
library(tidyverse)
library(broom)

theme_set(theme_bw())
cbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

data wrangling
```{r data wrangling}
# this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
# setwd(this.dir)
source("helpers.R")

read_csv("../data/EvidentialConfidenceSpeaker.csv") -> rawdata

rawdata <- rawdata %>% 
  rename(timestamp = Timestamp,
         ProlificID = "Enter your Prolific ID.",
         birthmonth = "Select your birth month.")

data <- rawdata %>% 
  pivot_longer(!timestamp:birthmonth, names_to = "context", values_to = "response",
               values_drop_na = TRUE)

#Identify lists
data <- data %>% 
  mutate(list = case_when(birthmonth == "January" | birthmonth =="July" ~ 1,
                          birthmonth == "February" | birthmonth =="August" ~ 2,
                          birthmonth == "March" | birthmonth =="September" ~ 3,
                          birthmonth == "April" | birthmonth =="October" ~ 4,
                          birthmonth == "May" | birthmonth =="November" ~ 5,
                          birthmonth == "June" | birthmonth =="December" ~ 6,
                          ))

#Identify conditions
data <- data %>% 
  separate(context,into = c("sense","perceptibility","property"),sep="_") %>% 
  separate(property, into = c("property"),sep="[.]")

data <- data %>% mutate(participant = match(ProlificID, unique(ProlificID)))

data <- data %>% select(!timestamp:birthmonth)

data %>% mutate_if(is.character,str_replace_all,pattern="mix",replacement="filler") %>% 
  mutate_if(is.character,str_replace_all,pattern="smell",replacement="filler") %>%
  mutate_if(is.character,str_replace_all,pattern="sign",replacement="filler") -> data

data %>% group_by(list) %>% tally(n()/12)

data %>% group_by(sense,perceptibility) %>% tally()

#Identify response types
data <- data %>% 
  mutate(response_type = if_else(
    str_detect(string=response, pattern="It's"),"bare","evidential"))

data %>% group_by(sense,response_type) %>% tally()
data %>% group_by(perceptibility,response_type) %>% tally()

cleandata <- data %>% 
  select(participant,sense,perceptibility,property,response_type) %>% 
  filter(sense!="filler") %>% 
  mutate(response_type=factor(response_type, levels=c("bare","evidential")),
         perceptibility=factor(perceptibility, levels=c("good","bad")),
         sense=factor(sense))


```

Read norms out of Lynott & Connell 2009
``` {r norms}
read_csv("../data/AdjMod.csv") -> AdjMod
AdjMod  %>%  
  select(Property,VisualStrengthMean,AuditoryStrengthMean,HapticStrengthMean) %>% 
  rename(property=Property,
         VisStr=VisualStrengthMean,
         AudStr=AuditoryStrengthMean,
         HapStr=HapticStrengthMean)-> AdjMod

left_join(cleandata,AdjMod,by="property") -> cleandata

#Match modality strength to evidence type
cleandata %>% 
  mutate(perceptual_strength = case_when(
    sense == "auditory" ~ AudStr,
    sense == "haptic" ~ HapStr,
    sense == "visual" ~ VisStr)) -> cleandata

cleandata %>% select(sense,VisStr:perceptual_strength)

#Standardize & square modality strength
cleandata <- cleandata %>% 
  mutate(perc_str_c = perceptual_strength-mean(perceptual_strength)) %>% 
  mutate(perc_str_z = perc_str_c / sd(perc_str_c)) %>% 
  mutate(perc_str_zsq = perc_str_z^2)

#Responses into 1 & 0
cleandata <- cleandata %>% 
  select(!VisStr:HapStr) %>% 
  mutate(evid_marking = if_else(response_type=="evidential",1,0)) %>% 
  mutate(evid_marking = as.integer(evid_marking),
         response_type = as.factor(response_type))
```

descriptive statistics
``` {r descriptive statistics}
cleandata %>% 
  group_by(sense,perceptibility) %>% 
  summarize("p(marking)"=round(mean(evid_marking),2)) %>%
  ungroup()

#Perceptual strength by quadrants
quantile(cleandata$perceptual_strength)

cleandata <- cleandata %>% 
  mutate(perc_str_q = case_when(perceptual_strength >= 
                                    quantile(perceptual_strength)[4]~ "Q4",
                                  perceptual_strength >= 
                                    quantile(perceptual_strength)[3] &
                                    perceptual_strength < 
                                    quantile(perceptual_strength)[4]~ "Q3",
                                  perceptual_strength >= 
                                    quantile(perceptual_strength)[2] &
                                    perceptual_strength < 
                                    quantile(perceptual_strength)[3]~ "Q2",
                                  perceptual_strength < 
                                    quantile(perceptual_strength)[2]~ "Q1")) 

cleandata %>% 
  group_by(perceptibility,perc_str_q) %>%
  summarize("p(marking)"=round(mean(evid_marking),2),n=n()) %>% 
  ungroup()
```

visualization
```{r visualization}
agr = cleandata %>% 
  group_by(perceptibility,perceptual_strength,sense) %>%
  summarize(evid_marking=mean(evid_marking))

ggplot(agr,aes(x=perceptual_strength, y=evid_marking, color=perceptibility,linetype=perceptibility))+
  geom_point(aes(shape=sense)) +
  geom_smooth(data=cleandata %>% filter(perceptibility == "bad"),method="lm") +
  geom_smooth(data=cleandata %>% filter(perceptibility == "good"),group=1) +
  scale_color_manual(name="Perceptibility\nconditions",values=cbPalette[5:6]) +
  scale_linetype(name="Perceptibility\nconditions") +
  scale_shape(name="Sense") +
  ylab("Proportion of evidential device uses") +
  xlab("Perceptual strength")
ggsave("../graphs/exp2-evid-uses.pdf",width=5,height=3)
```
smooth separately by sense -- not enough power
```{r visualization}
agr = cleandata %>% 
  group_by(perceptibility,perceptual_strength,sense) %>%
  summarize(evid_marking=mean(evid_marking))

ggplot(agr,aes(x=perceptual_strength, y=evid_marking, color=perceptibility,linetype=perceptibility))+
  geom_point(aes(shape=sense)) +
  # geom_smooth(data=cleandata %>% filter(perceptibility == "bad"),method="lm") +
  # geom_smooth(data=cleandata %>% filter(perceptibility == "good"),group=1) +
  geom_smooth() +
  scale_color_manual(name="Perceptibility\nconditions",values=cbPalette[5:6]) +
  scale_linetype(name="Perceptibility\nconditions") +
  scale_shape(name="Sense") +
  ylab("Proportion of evidential device uses") +
  xlab("Perceptual strength") +
  facet_wrap(~sense)
```

```{r visualization}
#Scatter plots
cleandata %>% 
  ggplot(aes(x=perceptual_strength, y=evid_marking, color=perceptibility))+
  scale_color_manual(values=c("#00BFC4","#F8766D"))+
  geom_point(position = position_jitter(height=0.1, width=0.1), alpha=0.7)+
  scale_y_discrete(limits=c(1,0))+
  geom_smooth()

cleandata %>% 
  ggplot(aes(x=perceptual_strength, y=evid_marking))+
  geom_point(position = position_jitter(height=0.1, width=0.1), alpha=0.5)+
  scale_y_discrete(limits=c(1,0))+
  facet_grid(~ perceptibility)+
  geom_smooth()

#Barplot by quadrant
cleandata %>% 
  group_by(perceptibility,perc_str_q) %>%
  summarize(evid_marking=round(mean(evid_marking),2),n=n()) %>% 
  ungroup()%>%  
  ggplot(aes(x=perc_str_q,y=evid_marking, fill=perceptibility))+
  geom_col(position="dodge",width=.5)+
  scale_fill_manual(values=c("#00B050","#C00000"),name="Perceptibility 
conditions") +
  theme_minimal()

```

statistical analysis
``` {r statistical analysis}
#dummy coding: bare utterance & good perceptibility as baseline
levels(cleandata$response_type)
contrasts(cleandata$response_type)

levels(cleandata$perceptibility)
contrasts(cleandata$perceptibility)

#sum / effect coding: visual as reference
levels(cleandata$sense)
contrasts(cleandata$sense) <- contr.sum(3)

#model w/ polynomial
speaker1 <- glmer(response_type ~ perc_str_z + perc_str_zsq + perceptibility + sense +
                    perceptibility:perc_str_z + perceptibility:perc_str_zsq +
                    (1|participant) + (1|property),
                  data = cleandata, family = "binomial")
summary(speaker1)

```
Model with centered perceptual strength, centered perceptibility
```{r}
d_model = cleandata %>% 
  mutate(cperceptibility = as.numeric(perceptibility) - mean(as.numeric(perceptibility)),
         cperceptual_strength = perceptual_strength - mean(perceptual_strength)) 

m <- glmer(response_type ~ cperceptual_strength * cperceptibility + sense + (1|participant),
                  data = d_model, family = "binomial")
summary(m)

```
Model with centered perceptual strength, centered perceptibility, and 2nd order perceptual strength polynomial term
```{r}
d_model = cleandata %>% 
  mutate(cperceptibility = as.numeric(perceptibility) - mean(as.numeric(perceptibility)),
         cperceptual_strength = perceptual_strength - mean(perceptual_strength)) 

m.poly <- glmer(response_type ~ poly(cperceptual_strength,2,raw=T) * cperceptibility + (1|participant) + (1|property),
                  data = d_model, family = "binomial")
summary(m.poly)
```
